version: "3.9"

services:
  database_devapi:
    image: mongo
    container_name: database_devapi
    restart: always
    ports:
      - 27017:27017
  app:
    build: .
    container_name: devapi
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database_devapi
    depends_on:
      - database_devapi
